In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [16]:
df = pd.read_csv(
    "../../employee_data_cleaned.csv"
)

df.head()

,Employee_ID,Name,Gender,Age,Department,City,Experience_Years,Education_Level,Job_Level,Salary,Performance_Score,Joining_Date,Is_Remote,Employment_Type,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score,Attrition,Email
0,1001,Farhan Ahmed,Male,38.0,Marketing,Karachi,4,Intermediate,Senior,111512.0,7.900000,2014-09-18,True,Full-time,169,150,77,1.1,No,farhan.ahmed1001@company.com
1,1002,Farhan Chaudhry,Female,35.0,Design,Rawalpindi,8,Intermediate,Senior,111512.0,6.700000,2017-06-27,True,Part-time,183,7,11,2.5,No,farhan.chaudhry1002@company.com
2,1003,Hira Sheikh,Female,23.0,Design,Lahore,3,MPhil,Junior,56050.0,7.443687,2015-07-24,True,Full-time,177,6,29,4.5,No,hira.sheikh1003@company.com
3,1004,Saad Butt,Female,42.0,Support,Islamabad,6,Master,Senior,118533.0,7.443687,2017-11-02,True,Full-time,188,18,71,1.9,No,unknown@company.com
4,1005,Shahzaib Qureshi,Male,35.0,IT,Peshawar,10,MPhil,Junior,77905.0,9.300000,2021-01-21,True,Full-time,190,30,18,NaN,No,shahzaib.qureshi1005@company.com

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 500
Columns: 20

In [18]:
df.columns

Index(['Employee_ID', 'Name', 'Gender', 'Age', 'Department', 'City',
       'Experience_Years', 'Education_Level', 'Job_Level', 'Salary',
       'Performance_Score', 'Joining_Date', 'Is_Remote', 'Employment_Type',
       'Monthly_Work_Hours', 'Projects_Completed', 'Training_Hours',
       'Satisfaction_Score', 'Attrition', 'Email'],
      dtype='str')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         500 non-null    int64
 1   Name                500 non-null    str
 2   Gender              500 non-null    str
 3   Age                 500 non-null    float64
 4   Department          500 non-null    str
 5   City                500 non-null    str
 6   Experience_Years    500 non-null    int64
 7   Education_Level     500 non-null    str
 8   Job_Level           500 non-null    str
 9   Salary              500 non-null    float64
 10  Performance_Score   500 non-null    float64
 11  Joining_Date        488 non-null    str
 12  Is_Remote           500 non-null    bool
 13  Employment_Type     500 non-null    str
 14  Monthly_Work_Hours  500 non-null    int64
 15  Projects_Completed  500 non-null    int64
 16  Training_Hours      500 non-null    int64
 17  Satisfaction_Score  482 non-null    float64
 18  Attrition           500 non-null    str
 19  Email               500 non-null    str
dtypes: bool(1), float64(4), int64(5), str(10)
memory usage: 74.8 KB

In [20]:
df.describe()

,Employee_ID,Age,Experience_Years,Salary,Performance_Score,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score
count,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.000000,500.000000,482.000000
mean,1250.500000,40.776000,10.560000,1.319680e+05,7.462147,184.886000,19.742000,40.420000,3.024896
std,144.481833,10.813866,7.067269,1.115442e+05,1.452858,25.580103,22.400156,23.889852,1.167261
min,1001.000000,5.000000,0.000000,3.922100e+04,5.000000,140.000000,1.000000,0.000000,1.000000
25%,1125.750000,33.000000,4.000000,8.415025e+04,6.200000,163.000000,9.000000,19.750000,2.000000
50%,1250.500000,42.000000,10.000000,1.115120e+05,7.443687,186.000000,19.000000,41.000000,3.100000
75%,1375.250000,49.000000,16.000000,1.510568e+05,8.700000,206.250000,28.000000,62.000000,4.000000
max,1500.000000,120.000000,25.000000,1.250000e+06,9.900000,230.000000,300.000000,80.000000,5.000000

In [27]:
df.isnull().sum()

Employee_ID            0
Name                   0
Gender                 0
Age                    0
Department             0
City                   0
Experience_Years       0
Education_Level        0
Job_Level              0
Salary                 0
Performance_Score      0
Joining_Date          12
Is_Remote              0
Employment_Type        0
Monthly_Work_Hours     0
Projects_Completed     0
Training_Hours         0
Satisfaction_Score     0
Attrition              0
Email                  0
dtype: int64

In [22]:
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(
    df["Satisfaction_Score"].median()
)

df["Satisfaction_Score"].isnull().sum()

np.int64(0)

In [28]:
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

df["Joining_Date"].isnull().sum()

np.int64(12)

In [29]:
df["Joining_Year"] = df["Joining_Date"].dt.year

df["Joining_Year"].isnull().sum()

np.int64(12)

In [30]:
df["Joining_Year"] = df["Joining_Year"].fillna(
    df["Joining_Year"].median()
)

df["Joining_Year"].isnull().sum()

np.int64(0)

In [23]:
df.duplicated().sum()

np.int64(0)

In [31]:
df = df.drop(
    columns=["Employee_ID", "Name", "Email", "Joining_Date"]
)

df.head()

,Gender,Age,Department,City,Experience_Years,Education_Level,Job_Level,Salary,Performance_Score,Is_Remote,Employment_Type,Monthly_Work_Hours,Projects_Completed,Training_Hours,Satisfaction_Score,Attrition,Joining_Year
0,Male,38.0,Marketing,Karachi,4,Intermediate,Senior,111512.0,7.900000,True,Full-time,169,150,77,1.1,No,2014.0
1,Female,35.0,Design,Rawalpindi,8,Intermediate,Senior,111512.0,6.700000,True,Part-time,183,7,11,2.5,No,2017.0
2,Female,23.0,Design,Lahore,3,MPhil,Junior,56050.0,7.443687,True,Full-time,177,6,29,4.5,No,2015.0
3,Female,42.0,Support,Islamabad,6,Master,Senior,118533.0,7.443687,True,Full-time,188,18,71,1.9,No,2017.0
4,Male,35.0,IT,Peshawar,10,MPhil,Junior,77905.0,9.300000,True,Full-time,190,30,18,3.1,No,2021.0

In [32]:
df["Attrition"].value_counts()

Attrition
No     405
Yes     95
Name: count, dtype: int64

In [33]:
df["Attrition"] = df["Attrition"].map({
    "No": 0,
    "Yes": 1
})

df["Attrition"].value_counts()

Attrition
0    405
1     95
Name: count, dtype: int64

In [34]:
X = df.drop(columns=["Attrition"])
y = df["Attrition"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (500, 16)
y shape: (500,)

In [35]:
X.select_dtypes(include="str").columns

Index(['Gender', 'Department', 'City', 'Education_Level', 'Job_Level',
       'Employment_Type'],
      dtype='str')

In [36]:
X = pd.get_dummies(X, drop_first=True)

X.shape

(500, 33)

In [37]:
X.dtypes

Age                             float64
Experience_Years                  int64
Salary                          float64
Performance_Score               float64
Is_Remote                          bool
Monthly_Work_Hours                int64
Projects_Completed                int64
Training_Hours                    int64
Satisfaction_Score              float64
Joining_Year                    float64
Gender_Male                        bool
Department_Finance                 bool
Department_HR                      bool
Department_IT                      bool
Department_Marketing               bool
Department_Operations              bool
Department_Sales                   bool
Department_Support                 bool
City_Islamabad                     bool
City_Karachi                       bool
City_Lahore                        bool
City_Multan                        bool
City_Peshawar                      bool
City_Rawalpindi                    bool
Education_Level_Intermediate       bool
Education_Level_MPhil              bool
Education_Level_Master             bool
Job_Level_Lead                     bool
Job_Level_Manager                  bool
Job_Level_Mid                      bool
Job_Level_Senior                   bool
Employment_Type_Full-time          bool
Employment_Type_Part-time          bool
dtype: object

In [39]:
X = X.astype(int)

X.dtypes

Age                             int64
Experience_Years                int64
Salary                          int64
Performance_Score               int64
Is_Remote                       int64
Monthly_Work_Hours              int64
Projects_Completed              int64
Training_Hours                  int64
Satisfaction_Score              int64
Joining_Year                    int64
Gender_Male                     int64
Department_Finance              int64
Department_HR                   int64
Department_IT                   int64
Department_Marketing            int64
Department_Operations           int64
Department_Sales                int64
Department_Support              int64
City_Islamabad                  int64
City_Karachi                    int64
City_Lahore                     int64
City_Multan                     int64
City_Peshawar                   int64
City_Rawalpindi                 int64
Education_Level_Intermediate    int64
Education_Level_MPhil           int64
Education_Level_Master          int64
Job_Level_Lead                  int64
Job_Level_Manager               int64
Job_Level_Mid                   int64
Job_Level_Senior                int64
Employment_Type_Full-time       int64
Employment_Type_Part-time       int64
dtype: object

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (400, 33)
X_test: (100, 33)
y_train: (400,)
y_test: (100,)

In [41]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training data:", X_train_scaled.shape)
print("Scaled testing data:", X_test_scaled.shape)

Scaled training data: (400, 33)
Scaled testing data: (100, 33)

In [42]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [43]:
y_pred = logistic_model.predict(X_test_scaled)

print("Predictions:", y_pred[:10])

Predictions: [0 0 0 0 0 0 0 0 0 0]

In [44]:
print("Actual:", y_test[:10].values)
print("Predicted:", y_pred[:10])

Actual: [0 0 0 0 0 0 0 0 0 1]
Predicted: [0 0 0 0 0 0 0 0 0 0]

In [45]:
print("Predicted class counts:")
print(pd.Series(y_pred).value_counts())

print("\nActual class counts:")
print(pd.Series(y_test).value_counts())

Predicted class counts:
0    98
1     2
Name: count, dtype: int64

Actual class counts:
Attrition
0    81
1    19
Name: count, dtype: int64

In [46]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[79  2]
 [19  0]]

In [47]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.98      0.88        81
           1       0.00      0.00      0.00        19

    accuracy                           0.79       100
   macro avg       0.40      0.49      0.44       100
weighted avg       0.65      0.79      0.71       100

In [48]:
logistic_balanced = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight="balanced"
)

logistic_balanced.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [49]:
y_pred_balanced = logistic_balanced.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred_balanced))
print(classification_report(y_test, y_pred_balanced))

[[37 44]
 [ 6 13]]
              precision    recall  f1-score   support

           0       0.86      0.46      0.60        81
           1       0.23      0.68      0.34        19

    accuracy                           0.50       100
   macro avg       0.54      0.57      0.47       100
weighted avg       0.74      0.50      0.55       100

In [50]:
print("Training target distribution:")
print(y_train.value_counts())

print("\nTraining target percentage:")
print(y_train.value_counts(normalize=True) * 100)

Training target distribution:
Attrition
0    324
1     76
Name: count, dtype: int64

Training target percentage:
Attrition
0    81.0
1    19.0
Name: proportion, dtype: float64

In [51]:
from sklearn.metrics import roc_auc_score

y_prob = logistic_model.predict_proba(X_test_scaled)[:, 1]

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.5399610136452242

In [52]:
y_prob_balanced = logistic_balanced.predict_proba(X_test_scaled)[:, 1]

auc_balanced = roc_auc_score(y_test, y_prob_balanced)

print("Balanced ROC-AUC:", auc_balanced)

Balanced ROC-AUC: 0.530214424951267

In [54]:
# Predict probabilities for the positive class (Attrition = 1)
y_proba = logistic_model.predict_proba(X_test_scaled)[:, 1]

# Display first 10 probabilities
print("Predicted probabilities:")
print(y_proba[:10])

Predicted probabilities:
[0.09049858 0.20140668 0.35310096 0.28921745 0.11394732 0.29360741
 0.2357583  0.20113998 0.13885479 0.0675588 ]

In [55]:
# Set a lower classification threshold
threshold = 0.30

# Convert probabilities into class predictions
y_pred_threshold = (y_proba >= threshold).astype(int)

# Show predictions
print("Predictions with threshold 0.30:")
print(y_pred_threshold)

# Show class counts
print("\nPredicted class counts:")
print(pd.Series(y_pred_threshold).value_counts())

Predictions with threshold 0.30:
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0
 1 0 1 1 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]

Predicted class counts:
0    80
1    20
Name: count, dtype: int64

In [56]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

# Confusion matrix
cm_threshold = confusion_matrix(y_test, y_pred_threshold)

print("Confusion Matrix:")
print(cm_threshold)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_threshold))

# ROC-AUC remains based on probabilities
roc_auc_threshold = roc_auc_score(y_test, y_proba)

print("\nROC-AUC:", roc_auc_threshold)

Confusion Matrix:
[[64 17]
 [16  3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.79      0.80        81
           1       0.15      0.16      0.15        19

    accuracy                           0.67       100
   macro avg       0.48      0.47      0.47       100
weighted avg       0.68      0.67      0.67       100


ROC-AUC: 0.5399610136452242

Logistic Regression achieved 79% accuracy with the default threshold, but failed to detect any Attrition cases due to class imbalance. Class balancing significantly improved Attrition recall to 68%, although accuracy decreased to 50%. Lowering the classification threshold to 0.30 produced 67% accuracy but only 16% Attrition recall. The ROC-AUC remained around 0.54, indicating weak overall discriminative performance.