In [1]:
# Import required libraries
import numpy as np
import pandas as pd

In [3]:
# Load the original Heart Failure dataset
df = pd.read_csv(
    "../heart_failure_clinical_records_dataset-selected-columns.csv"
)

df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex
0,75.0,0,582,0,20,1,265000.00,1.9,130,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0

In [4]:
# Verify the original dataset
print("Dataset Shape:", df.shape)
print("Total Missing Values:", df.isnull().sum().sum())

Dataset Shape: (299, 10)
Total Missing Values: 0

In [5]:
# Create an independent copy
df_missing = df.copy()

# Introduce missing values into selected columns
df_missing.loc[5:14, "age"] = np.nan

df_missing.loc[
    [20, 25, 30, 35, 40],
    "serum_creatinine"
] = np.nan

df_missing.loc[
    [50, 55, 60, 65],
    "platelets"
] = np.nan

df_missing.loc[
    [70, 75, 80],
    "diabetes"
] = np.nan

# Display missing-value counts
df_missing.isnull().sum()

age                         10
anaemia                      0
creatinine_phosphokinase     0
diabetes                     3
ejection_fraction            0
high_blood_pressure          0
platelets                    4
serum_creatinine             5
serum_sodium                 0
sex                          0
dtype: int64

In [6]:
# Store the original size of the practice DataFrame
starting_rows = df_missing.shape[0]
starting_columns = df_missing.shape[1]

print("Starting Rows:", starting_rows)
print("Starting Columns:", starting_columns)
print(
    "Starting Missing Values:",
    df_missing.isnull().sum().sum()
)

Starting Rows: 299
Starting Columns: 10
Starting Missing Values: 22

In [7]:
# Create a separate copy for Row Deletion
df_row_deleted = df_missing.copy()

# Remove rows containing at least one missing value
df_row_deleted = df_row_deleted.dropna()

print("Shape Before Row Deletion:", df_missing.shape)
print("Shape After Row Deletion:", df_row_deleted.shape)

Shape Before Row Deletion: (299, 10)
Shape After Row Deletion: (277, 10)

In [8]:
# Calculate row loss
rows_before = df_missing.shape[0]
rows_after = df_row_deleted.shape[0]

rows_removed = rows_before - rows_after

row_loss_percentage = (
    rows_removed / rows_before
) * 100

print("Rows Removed:", rows_removed)
print(
    f"Row Data Loss: {row_loss_percentage:.2f}%"
)

Rows Removed: 22
Row Data Loss: 7.36%

In [9]:
# Verify missing values after Row Deletion
print(
    "Remaining Missing Values:",
    df_row_deleted.isnull().sum().sum()
)

df_row_deleted.isnull().sum()

Remaining Missing Values: 0

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
dtype: int64

In [10]:
# Create a separate copy for Column Deletion
df_column_example = df_missing.copy()

# Create a practice column containing mostly missing values
df_column_example["optional_test"] = np.nan

# Keep values in only a small number of rows
df_column_example.loc[
    0:39,
    "optional_test"
] = 1

# Calculate missing percentage
optional_test_missing_percentage = (
    df_column_example["optional_test"]
    .isnull()
    .mean()
    * 100
)

print(
    "optional_test Missing Percentage:",
    f"{optional_test_missing_percentage:.2f}%"
)

optional_test Missing Percentage: 86.62%

In [11]:
# Remove the highly incomplete practice column
df_column_deleted = df_column_example.drop(
    columns=["optional_test"]
)

print(
    "Columns Before Deletion:",
    df_column_example.shape[1]
)

print(
    "Columns After Deletion:",
    df_column_deleted.shape[1]
)

print(
    "optional_test Exists:",
    "optional_test" in df_column_deleted.columns
)

Columns Before Deletion: 11
Columns After Deletion: 10
optional_test Exists: False

In [12]:
# Require at least 50% non-missing values
minimum_non_missing = (
    len(df_column_example) * 0.5
)

df_threshold_cleaned = df_column_example.dropna(
    axis=1,
    thresh=minimum_non_missing
)

print(
    "Minimum Required Non-Missing Values:",
    minimum_non_missing
)

print(
    "optional_test Exists After Threshold:",
    "optional_test" in df_threshold_cleaned.columns
)

Minimum Required Non-Missing Values: 149.5
optional_test Exists After Threshold: False

In [13]:
# Create a separate copy for Selective Deletion
df_selective_deleted = df_missing.copy()

critical_columns = [
    "age",
    "serum_creatinine"
]

# Remove rows only when critical columns are missing
df_selective_deleted = (
    df_selective_deleted.dropna(
        subset=critical_columns
    )
)

print(
    "Shape Before Selective Deletion:",
    df_missing.shape
)

print(
    "Shape After Selective Deletion:",
    df_selective_deleted.shape
)

Shape Before Selective Deletion: (299, 10)
Shape After Selective Deletion: (284, 10)

In [14]:
# Other columns may still contain missing values
df_selective_deleted.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    3
ejection_fraction           0
high_blood_pressure         0
platelets                   4
serum_creatinine            0
serum_sodium                0
sex                         0
dtype: int64

In [15]:
# Calculate selective row loss
selective_rows_removed = (
    len(df_missing)
    - len(df_selective_deleted)
)

selective_loss_percentage = (
    selective_rows_removed
    / len(df_missing)
) * 100

print(
    "Rows Removed Selectively:",
    selective_rows_removed
)

print(
    f"Selective Data Loss: "
    f"{selective_loss_percentage:.2f}%"
)

Rows Removed Selectively: 15
Selective Data Loss: 5.02%

In [16]:
# Create a comparison table
comparison = pd.DataFrame({
    "Method": [
        "Original Practice Data",
        "Complete Row Deletion",
        "Selective Deletion",
        "Column Deletion Example"
    ],
    "Rows": [
        df_missing.shape[0],
        df_row_deleted.shape[0],
        df_selective_deleted.shape[0],
        df_column_deleted.shape[0]
    ],
    "Columns": [
        df_missing.shape[1],
        df_row_deleted.shape[1],
        df_selective_deleted.shape[1],
        df_column_deleted.shape[1]
    ],
    "Missing Values": [
        df_missing.isnull().sum().sum(),
        df_row_deleted.isnull().sum().sum(),
        df_selective_deleted.isnull().sum().sum(),
        df_column_deleted.isnull().sum().sum()
    ]
})

comparison

                    Method  Rows  Columns  Missing Values
0   Original Practice Data   299       10              22
1    Complete Row Deletion   277       10               0
2       Selective Deletion   284       10               7
3  Column Deletion Example   299       10              22

In [17]:
# Confirm the original DataFrame was not changed
print("Original Shape:", df.shape)

print(
    "Original Missing Values:",
    df.isnull().sum().sum()
)

Original Shape: (299, 10)
Original Missing Values: 0

# Summary

In this notebook, we:

- Preserved the original Heart Failure dataset
- Created missing values in a separate practice copy
- Removed all incomplete rows using Row Deletion
- Measured row-level data loss
- Created and removed a highly incomplete practice column
- Applied threshold-based Column Deletion
- Removed rows based only on critical columns
- Compared the effects of all removal methods
- Confirmed that the original dataset remained unchanged

## Key Learnings

- Row Deletion removes complete incomplete records.
- Column Deletion removes an entire feature.
- Selective Deletion uses specific critical columns.
- Removal should not be applied without measuring data loss.
- Selective Deletion usually provides more control than blind Row Deletion.